name: CMake Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -G Xcode -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES="arm64" -DBUILD_SHARED_LIBS=OFF

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ runner.job_count }}

      - name: Install
        run: cmake --install build --config ${{ matrix.build_type }}

      # No test step, can't test iOS (especially without the simulator arch)
      # If you figure out how to do this easily, i'll buy you a beer.

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iOS-${{ matrix.os }}-${{ matrix.build_type }}
          path: install/**
          if-no-files-found: error
