# .github/workflows/build.yml
name: CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest, macos-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: ${{ runner.job_count }}

      - name: Install
        run: cmake --install build --config ${{ matrix.build_type }}

      - name: Test
        run: |
          dotnet restore ./InteropTestsXUnit.csproj --source ../ConnectedSpacesPlatform_Unity_Nuget/bin/${{matrix.build_type}} --source https://api.nuget.org/v3/index.json
          dotnet test -c ${{ matrix.build_type }}
        working-directory: ./InteropTestsXUnit
